// Central registry of TanStack Query keys - extend here when adding a feature
export const qk = Object.freeze({
  auth: {
    me: () => ["auth", "me"],
  },
  users: {
    all: () => ["users"],
    list: (params) => ["users", "list", params],
    one: (id) => ["users", "detail", id],
  },
  activityLogs: {
    all: () => ["activityLogs"],
    list: (params) => ["activityLogs", "list", params],
    one: (id) => ["activityLogs", "detail", id],
    stats: (params) => ["activityLogs", "stats", params],
  },
  soliq: {
    all: () => ["soliq"],
    taxpayers: (params) => ["soliq", "taxpayers", params],
    taxpayer: (id) => ["soliq", "taxpayer", id],
    assessments: (params) => ["soliq", "assessments", params],
    debtors: (params) => ["soliq", "debtors", params],
    locations: (params) => ["soliq", "locations", params],
    summary: (params) => ["soliq", "summary", params],
    timeseries: (params) => ["soliq", "timeseries", params],
    breakdown: (params) => ["soliq", "breakdown", params],
    mahalla: (params) => ["soliq", "mahalla", params],
  },
  yer: {
    all: () => ["yer"],
    properties: (params) => ["yer", "properties", params],
    property: (id) => ["yer", "property", id],
    requests: (params) => ["yer", "requests", params],
    request: (id) => ["yer", "request", id],
    myProperties: () => ["yer", "my", "properties"],
    myRequests: () => ["yer", "my", "requests"],
    registry: (cadastreNumber) => ["yer", "registry", cadastreNumber],
    analytics: (kind, params) => ["yer", "analytics", kind, params],
  },
  gaz: {
    all: () => ["gaz"],
    subscribers: (params) => ["gaz", "subscribers", params],
    subscriber: (id) => ["gaz", "subscriber", id],
    requests: (params) => ["gaz", "requests", params],
    request: (id) => ["gaz", "request", id],
    payments: (params) => ["gaz", "payments", params],
    debtors: (params) => ["gaz", "debtors", params],
    tariff: () => ["gaz", "tariff"],
    registry: (accountNumber) => ["gaz", "registry", accountNumber],
    analytics: (kind, params) => ["gaz", "analytics", kind, params],
  },
  elektr: {
    all: () => ["elektr"],
    analytics: (kind, params) => ["elektr", "analytics", kind, params],
  },
  msk: {
    all: () => ["msk"],
    appeals: (params) => ["msk", "appeals", params],
    appeal: (id) => ["msk", "appeal", id],
    analytics: (kind, params) => ["msk", "analytics", kind, params],
  },
  svet: {
    all: () => ["svet"],
    subscribers: (params) => ["svet", "subscribers", params],
    subscriber: (id) => ["svet", "subscriber", id],
    requests: (params) => ["svet", "requests", params],
    request: (id) => ["svet", "request", id],
    violations: (params) => ["svet", "violations", params],
    account: (accountNumber) => ["svet", "account", accountNumber],
    analytics: (kind, params) => ["svet", "analytics", kind, params],
  },
  murojaat: {
    all: () => ["murojaat"],
    appeals: (params) => ["murojaat", "appeals", params],
    appeal: (id) => ["murojaat", "appeal", id],
    organizations: () => ["murojaat", "organizations"],
    myAppeals: () => ["murojaat", "my", "appeals"],
    track: (appealNumber) => ["murojaat", "track", appealNumber],
    analytics: (kind, params) => ["murojaat", "analytics", kind, params],
  },
});
