export const ENDPOINTS = Object.freeze({
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    registerUser: "/auth/register-user",
  },
  users: {
    base: "/users",
    byId: (id) => `/users/${id}`,
  },
  activityLogs: {
    base: "/activity-logs",
    byId: (id) => `/activity-logs/${id}`,
    stats: "/activity-logs/stats",
  },
  soliq: {
    taxpayers: "/soliq/taxpayers",
    taxpayerById: (id) => `/soliq/taxpayers/${id}`,
    assessments: "/soliq/assessments",
    debtors: "/soliq/debtors",
    pay: (id) => `/soliq/assessments/${id}/pay`,
    locations: "/soliq/locations",
    summary: "/soliq/analytics/summary",
    timeseries: "/soliq/analytics/timeseries",
    breakdown: "/soliq/analytics/breakdown",
    mahalla: "/soliq/analytics/mahalla",
  },
  yer: {
    properties: "/yer/properties",
    propertyById: (id) => `/yer/properties/${id}`,
    requests: "/yer/requests",
    requestById: (id) => `/yer/requests/${id}`,
    registryCheck: "/yer/registry/check",
    myProperties: "/yer/my/properties",
    myRequests: "/yer/my/requests",
    analytics: {
      summary: "/yer/analytics/summary",
      timeseries: "/yer/analytics/timeseries",
      breakdown: "/yer/analytics/breakdown",
    },
  },
  gaz: {
    subscribers: "/gaz/subscribers",
    subscriberById: (id) => `/gaz/subscribers/${id}`,
    requests: "/gaz/requests",
    requestById: (id) => `/gaz/requests/${id}`,
    payments: "/gaz/payments",
    debtors: "/gaz/debtors",
    tariff: "/gaz/tariff",
    registryCheck: "/gaz/registry/check",
    analytics: {
      summary: "/gaz/analytics/summary",
      timeseries: "/gaz/analytics/timeseries",
      breakdown: "/gaz/analytics/breakdown",
    },
  },
  svet: {
    subscribers: "/svet/subscribers",
    subscriberById: (id) => `/svet/subscribers/${id}`,
    requests: "/svet/requests",
    requestById: (id) => `/svet/requests/${id}`,
    violations: "/svet/violations",
    accountCheck: "/svet/account/check",
    analytics: {
      summary: "/svet/analytics/summary",
      timeseries: "/svet/analytics/timeseries",
      breakdown: "/svet/analytics/breakdown",
    },
  },
  murojaat: {
    appeals: "/murojaat/appeals",
    appealById: (id) => `/murojaat/appeals/${id}`,
    organizations: "/murojaat/organizations",
    track: "/murojaat/track",
    myAppeals: "/murojaat/my/appeals",
    analytics: {
      summary: "/murojaat/analytics/summary",
      timeseries: "/murojaat/analytics/timeseries",
      breakdown: "/murojaat/analytics/breakdown",
    },
  },
});
